# Generated by Django 4.2.1 on 2023-06-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter category name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter manufacturer name', max_length=200)),
                ('country', models.CharField(max_length=20)),
                ('foundation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('l', 'Liters'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('boxes', 'Boxes'), ('packets', 'Packets'), ('jars', 'Jars'), ('slices', 'Slices'), ('servings', 'Servings'), ('m', 'Meters'), ('cm', 'Centimeters')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer')),
            ],
            options={
                'permissions': [('view_quantity', 'Can view quantity')],
            },
        ),
    ]
